baseURL = "https://stm32club.ru/"
languageCode = "ru-RU"
title = "STM32"
theme = "hugo-geekdoc"

enableGitInfo = true

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
uglyURLs = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]
  geekdocLogo = "logo.svg"
  geekdocRepo = "https://github.com/i7d3v3l0p3r/STM32"
  geekdocEditPath = "edit/master/content"

[frontmatter]
  lastmod = [":git", ":fileModTime", "lastmod", "date", "publishDate"]
